version: '2.1'
orbs:
  terraform: 'circleci/terraform@1.1.1'

jobs:
  terraform/fmt:
    checkout: true
    context: terraform

  terraform/validate:
    checkout: true
    context: terraform
    backend_config: "access_key=$(TF_VAR_accesskey),secret_key=$(TF_VAR_secretkey)"
    requires:
      - terraform/fmt

  terraform/plan:
    checkout: true
    context: terraform
    persist-workspace: true
    requires:
      - terraform/validate

  terraform/apply:
    attach-workspace: true
    context: terraform
    filters:
      branches:
        only: main
    requires:
      - terraform/plan

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform/fmt
      - terraform/validate
