version: '2.1'
orbs:
  terraform: 'circleci/terraform@1.1.1'
jobs:
  terraform/fmt:
    docker:
      - image: hashicorp/terraform:light
    checkout: true
    context: terraform
  terraform/validate:
    docker:
      - image: hashicorp/terraform:light
    checkout: true
    context: terraform
    backend_config: "access_key=$(TF_VAR_accesskey),secret_key=$(TF_VAR_secretkey)"
    requires:
      - terraform/fmt
  terraform/plan:
    docker:
      - image: hashicorp/terraform:light
    checkout: true
    context: terraform
    persist-workspace: true
    requires:
      - terraform/validate
  terraform/apply:
    docker:
      - image: hashicorp/terraform:light
    attach-workspace: true
    context: terraform
    filters:
      branches:
        only: main
    requires:
      - terraform/plan

workflows:
  deploy_infrastructure:

